//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class pav_condition
    {
        public string sectionId { get; set; }
        public string sectionId2 { get; set; }
        public string sectionId3 { get; set; }
        public string roadId { get; set; }
        public string direction { get; set; }
        public Nullable<int> laneCode { get; set; }
        public Nullable<double> fromKP { get; set; }
        public Nullable<double> toKP { get; set; }
        public Nullable<double> length { get; set; }
        public string structure { get; set; }
        public Nullable<int> pavType { get; set; }
        public string date { get; set; }
        public Nullable<double> crackFatigueL { get; set; }
        public Nullable<double> crackFatigueM { get; set; }
        public Nullable<double> crackFatigueH { get; set; }
        public Nullable<double> crackTransverseL { get; set; }
        public Nullable<double> crackTransverseM { get; set; }
        public Nullable<double> crackTransverseH { get; set; }
        public Nullable<double> crackMiscellanenousL { get; set; }
        public Nullable<double> crackMiscellanenousM { get; set; }
        public Nullable<double> crackMiscellanenousH { get; set; }
        public Nullable<double> rutDepth { get; set; }
        public Nullable<int> IRI { get; set; }
        public Nullable<int> TV { get; set; }
        public string BIC { get; set; }
        public string EIC { get; set; }
        public Nullable<int> status { get; set; }
    }
}
