//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public string MaLuong { get; set; }
        public string MaPhieuLuong { get; set; }
        public string MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public Nullable<int> ThangTraLuong { get; set; }
        public Nullable<System.DateTime> NgayNhanLuong { get; set; }
        public Nullable<long> Luong { get; set; }
        public string TrangThai { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEULUONG PHIEULUONG { get; set; }
    }
}
