//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGHOCPHI
    {
        public string MaHocPhi { get; set; }
        public string MaHoaDon { get; set; }
        public string MaHocSinh { get; set; }
        public string TenHocSinh { get; set; }
        public Nullable<int> ThangNop { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<long> SoTien { get; set; }
        public string TrangThai { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
