//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.BANGHOCPHIs = new HashSet<BANGHOCPHI>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHocSinhNop { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string MaHocSinh { get; set; }
        public string MaNhanVien { get; set; }
        public string ThangNop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGHOCPHI> BANGHOCPHIs { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
