//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHHOC()
        {
            this.DIEMDANHs = new HashSet<DIEMDANH>();
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
        }
    
        public string MaLichHoc { get; set; }
        public Nullable<System.DateTime> NgayHoc { get; set; }
        public string MaLop { get; set; }
        public Nullable<int> SiSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMDANH> DIEMDANHs { get; set; }
        public virtual LOP LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
    }
}
