//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.LICHHOCs = new HashSet<LICHHOC>();
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<int> TongSoBuoi { get; set; }
        public string MaKhoi { get; set; }
        public string MaGiaoVien { get; set; }
        public string MaLoaiLop { get; set; }
        public Nullable<int> SoHocSinh { get; set; }
        public Nullable<int> SoHSToiDa { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KHOI KHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHOC> LICHHOCs { get; set; }
        public virtual LOAILOP LOAILOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
    }
}
