//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEULUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEULUONG()
        {
            this.BANGLUONGs = new HashSet<BANGLUONG>();
        }
    
        public string MaPhieuLuong { get; set; }
        public Nullable<System.DateTime> NgayGiaoVienNhanLuong { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string MaGiaoVien { get; set; }
        public string MaNhanVien { get; set; }
        public string ThangTraLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGLUONG> BANGLUONGs { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
