//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWrireFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIKHOABIEU
    {
        public string MaLichHoc { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual LICHHOC LICHHOC { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
